// <auto-generated />
using System;
using Gymbokning.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Gymbokning.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210923170946_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Gymbokning.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TimeOfRegistration")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Gymbokning.Models.ApplicationUserGymClass", b =>
                {
                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("GymClassId")
                        .HasColumnType("int");

                    b.HasKey("ApplicationUserId", "GymClassId");

                    b.HasIndex("GymClassId");

                    b.ToTable("ApplicationUserGymClass");
                });

            modelBuilder.Entity("Gymbokning.Models.GymClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("GymClass");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Aerobics is a form of physical exercise that combines rhythmic aerobic exercise with stretching and strength training routines with the goal of improving all elements of fitness (flexibility, muscular strength, and cardio-vascular fitness).",
                            Duration = new TimeSpan(0, 1, 30, 0, 0),
                            Name = "Aerobics",
                            StartTime = new DateTime(2021, 9, 2, 19, 9, 46, 578, DateTimeKind.Local).AddTicks(6395)
                        },
                        new
                        {
                            Id = 2,
                            Description = "Pilates improves flexibility, builds strength and develops control and endurance in the entire body. It puts emphasis on alignment, breathing, developing a strong core, and improving coordination and balance.",
                            Duration = new TimeSpan(0, 1, 30, 0, 0),
                            Name = "Pilates",
                            StartTime = new DateTime(2021, 9, 4, 19, 9, 46, 580, DateTimeKind.Local).AddTicks(5879)
                        },
                        new
                        {
                            Id = 3,
                            Description = "Kickboxing is a group of stand-up combat sports based on kicking and punching, historically developed from karate mixed with boxing. Kickboxing is practiced for self-defence, general fitness, or as a contact sport.",
                            Duration = new TimeSpan(0, 1, 0, 0, 0),
                            Name = "Kickboxing",
                            StartTime = new DateTime(2021, 9, 4, 19, 9, 46, 580, DateTimeKind.Local).AddTicks(5902)
                        },
                        new
                        {
                            Id = 4,
                            Description = "High-intensity interval training (HIIT) is a form of interval training, a cardiovascular exercise strategy alternating short periods of intense anaerobic exercise with less intense recovery periods, until too exhausted to continue. The method is not just restricted to cardio and frequently includes weights for the short periods as well.",
                            Duration = new TimeSpan(0, 0, 30, 0, 0),
                            Name = "HIIT",
                            StartTime = new DateTime(2021, 9, 5, 19, 9, 46, 580, DateTimeKind.Local).AddTicks(5906)
                        },
                        new
                        {
                            Id = 5,
                            Description = "Yoga is a mind-body practice that combines physical poses, controlled breathing, and meditation or relaxation. Yoga may help reduce stress, lower blood pressure and lower your heart rate. And almost anyone can do it.",
                            Duration = new TimeSpan(0, 1, 0, 0, 0),
                            Name = "Yoga",
                            StartTime = new DateTime(2021, 9, 6, 19, 9, 46, 580, DateTimeKind.Local).AddTicks(5908)
                        },
                        new
                        {
                            Id = 6,
                            Description = "Zumba is an interval workout. The classes move between high- and low-intensity dance moves designed to get your heart rate up and boost cardio endurance.",
                            Duration = new TimeSpan(0, 1, 30, 0, 0),
                            Name = "Zumba",
                            StartTime = new DateTime(2021, 9, 7, 19, 9, 46, 580, DateTimeKind.Local).AddTicks(5910)
                        },
                        new
                        {
                            Id = 7,
                            Description = "Boredom and time constraints are frequently cited reasons for giving up on a fitness routine. Sound familiar? Circuit training offers a practical solution for both. It’s a creative and flexible way to keep exercise interesting and saves time while boosting cardiovascular and muscular fitness. ",
                            Duration = new TimeSpan(0, 0, 45, 0, 0),
                            Name = "Circuit",
                            StartTime = new DateTime(2021, 9, 8, 19, 9, 46, 580, DateTimeKind.Local).AddTicks(5913)
                        },
                        new
                        {
                            Id = 8,
                            Description = "Burn up to 1,000 calories while having a blast. Feel that oh-so-rewarding burn in your legs, arms, and core over an hour of fitness disguised as fun. It’s one of the most dynamic, effective, and enjoyable workouts you'll ever have.",
                            Duration = new TimeSpan(0, 0, 45, 0, 0),
                            Name = "Skyrobics",
                            StartTime = new DateTime(2021, 9, 8, 19, 9, 46, 580, DateTimeKind.Local).AddTicks(5915)
                        },
                        new
                        {
                            Id = 9,
                            Description = "Aerobics is a form of physical exercise that combines rhythmic aerobic exercise with stretching and strength training routines with the goal of improving all elements of fitness (flexibility, muscular strength, and cardio-vascular fitness).",
                            Duration = new TimeSpan(0, 1, 30, 0, 0),
                            Name = "Aerobics",
                            StartTime = new DateTime(2021, 9, 9, 19, 9, 46, 580, DateTimeKind.Local).AddTicks(5917)
                        },
                        new
                        {
                            Id = 10,
                            Description = "Pilates improves flexibility, builds strength and develops control and endurance in the entire body. It puts emphasis on alignment, breathing, developing a strong core, and improving coordination and balance.",
                            Duration = new TimeSpan(0, 1, 30, 0, 0),
                            Name = "Pilates",
                            StartTime = new DateTime(2021, 9, 10, 19, 9, 46, 580, DateTimeKind.Local).AddTicks(5919)
                        },
                        new
                        {
                            Id = 11,
                            Description = "Kickboxing is a group of stand-up combat sports based on kicking and punching, historically developed from karate mixed with boxing. Kickboxing is practiced for self-defence, general fitness, or as a contact sport.",
                            Duration = new TimeSpan(0, 1, 0, 0, 0),
                            Name = "Kickboxing",
                            StartTime = new DateTime(2021, 9, 11, 19, 9, 46, 580, DateTimeKind.Local).AddTicks(5921)
                        },
                        new
                        {
                            Id = 12,
                            Description = "High-intensity interval training (HIIT) is a form of interval training, a cardiovascular exercise strategy alternating short periods of intense anaerobic exercise with less intense recovery periods, until too exhausted to continue. The method is not just restricted to cardio and frequently includes weights for the short periods as well.",
                            Duration = new TimeSpan(0, 0, 30, 0, 0),
                            Name = "HIIT",
                            StartTime = new DateTime(2021, 9, 12, 19, 9, 46, 580, DateTimeKind.Local).AddTicks(5924)
                        },
                        new
                        {
                            Id = 13,
                            Description = "Yoga is a mind-body practice that combines physical poses, controlled breathing, and meditation or relaxation. Yoga may help reduce stress, lower blood pressure and lower your heart rate. And almost anyone can do it.",
                            Duration = new TimeSpan(0, 1, 0, 0, 0),
                            Name = "Yoga",
                            StartTime = new DateTime(2021, 9, 13, 19, 9, 46, 580, DateTimeKind.Local).AddTicks(5927)
                        },
                        new
                        {
                            Id = 14,
                            Description = "Zumba is an interval workout. The classes move between high- and low-intensity dance moves designed to get your heart rate up and boost cardio endurance.",
                            Duration = new TimeSpan(0, 1, 30, 0, 0),
                            Name = "Zumba",
                            StartTime = new DateTime(2021, 9, 7, 19, 9, 46, 580, DateTimeKind.Local).AddTicks(5929)
                        },
                        new
                        {
                            Id = 15,
                            Description = "Boredom and time constraints are frequently cited reasons for giving up on a fitness routine. Sound familiar? Circuit training offers a practical solution for both. It’s a creative and flexible way to keep exercise interesting and saves time while boosting cardiovascular and muscular fitness. ",
                            Duration = new TimeSpan(0, 0, 45, 0, 0),
                            Name = "Circuit",
                            StartTime = new DateTime(2021, 9, 14, 19, 9, 46, 580, DateTimeKind.Local).AddTicks(5931)
                        },
                        new
                        {
                            Id = 16,
                            Description = "Burn up to 1,000 calories while having a blast. Feel that oh-so-rewarding burn in your legs, arms, and core over an hour of fitness disguised as fun. It’s one of the most dynamic, effective, and enjoyable workouts you'll ever have.",
                            Duration = new TimeSpan(0, 0, 45, 0, 0),
                            Name = "Skyrobics",
                            StartTime = new DateTime(2021, 9, 15, 19, 9, 46, 580, DateTimeKind.Local).AddTicks(5933)
                        },
                        new
                        {
                            Id = 17,
                            Description = "Aerobics is a form of physical exercise that combines rhythmic aerobic exercise with stretching and strength training routines with the goal of improving all elements of fitness (flexibility, muscular strength, and cardio-vascular fitness).",
                            Duration = new TimeSpan(0, 1, 30, 0, 0),
                            Name = "Aerobics",
                            StartTime = new DateTime(2021, 9, 22, 19, 9, 46, 580, DateTimeKind.Local).AddTicks(5935)
                        },
                        new
                        {
                            Id = 18,
                            Description = "Pilates improves flexibility, builds strength and develops control and endurance in the entire body. It puts emphasis on alignment, breathing, developing a strong core, and improving coordination and balance.",
                            Duration = new TimeSpan(0, 1, 30, 0, 0),
                            Name = "Pilates",
                            StartTime = new DateTime(2021, 9, 24, 19, 9, 46, 580, DateTimeKind.Local).AddTicks(5938)
                        },
                        new
                        {
                            Id = 19,
                            Description = "Kickboxing is a group of stand-up combat sports based on kicking and punching, historically developed from karate mixed with boxing. Kickboxing is practiced for self-defence, general fitness, or as a contact sport.",
                            Duration = new TimeSpan(0, 1, 0, 0, 0),
                            Name = "Kickboxing",
                            StartTime = new DateTime(2021, 9, 25, 19, 9, 46, 580, DateTimeKind.Local).AddTicks(5940)
                        },
                        new
                        {
                            Id = 20,
                            Description = "High-intensity interval training (HIIT) is a form of interval training, a cardiovascular exercise strategy alternating short periods of intense anaerobic exercise with less intense recovery periods, until too exhausted to continue. The method is not just restricted to cardio and frequently includes weights for the short periods as well.",
                            Duration = new TimeSpan(0, 0, 30, 0, 0),
                            Name = "HIIT",
                            StartTime = new DateTime(2021, 9, 26, 19, 9, 46, 580, DateTimeKind.Local).AddTicks(5943)
                        },
                        new
                        {
                            Id = 21,
                            Description = "Yoga is a mind-body practice that combines physical poses, controlled breathing, and meditation or relaxation. Yoga may help reduce stress, lower blood pressure and lower your heart rate. And almost anyone can do it.",
                            Duration = new TimeSpan(0, 1, 0, 0, 0),
                            Name = "Yoga",
                            StartTime = new DateTime(2021, 9, 13, 19, 9, 46, 580, DateTimeKind.Local).AddTicks(5945)
                        },
                        new
                        {
                            Id = 22,
                            Description = "Zumba is an interval workout. The classes move between high- and low-intensity dance moves designed to get your heart rate up and boost cardio endurance.",
                            Duration = new TimeSpan(0, 1, 30, 0, 0),
                            Name = "Zumba",
                            StartTime = new DateTime(2021, 9, 7, 19, 9, 46, 580, DateTimeKind.Local).AddTicks(5947)
                        },
                        new
                        {
                            Id = 23,
                            Description = "Boredom and time constraints are frequently cited reasons for giving up on a fitness routine. Sound familiar? Circuit training offers a practical solution for both. It’s a creative and flexible way to keep exercise interesting and saves time while boosting cardiovascular and muscular fitness. ",
                            Duration = new TimeSpan(0, 0, 45, 0, 0),
                            Name = "Circuit",
                            StartTime = new DateTime(2021, 9, 27, 19, 9, 46, 580, DateTimeKind.Local).AddTicks(5949)
                        },
                        new
                        {
                            Id = 24,
                            Description = "Burn up to 1,000 calories while having a blast. Feel that oh-so-rewarding burn in your legs, arms, and core over an hour of fitness disguised as fun. It’s one of the most dynamic, effective, and enjoyable workouts you'll ever have.",
                            Duration = new TimeSpan(0, 0, 45, 0, 0),
                            Name = "Skyrobics",
                            StartTime = new DateTime(2021, 9, 28, 19, 9, 46, 580, DateTimeKind.Local).AddTicks(5951)
                        },
                        new
                        {
                            Id = 25,
                            Description = "Aerobics is a form of physical exercise that combines rhythmic aerobic exercise with stretching and strength training routines with the goal of improving all elements of fitness (flexibility, muscular strength, and cardio-vascular fitness).",
                            Duration = new TimeSpan(0, 1, 30, 0, 0),
                            Name = "Aerobics",
                            StartTime = new DateTime(2021, 9, 29, 19, 9, 46, 580, DateTimeKind.Local).AddTicks(5954)
                        },
                        new
                        {
                            Id = 26,
                            Description = "Pilates improves flexibility, builds strength and develops control and endurance in the entire body. It puts emphasis on alignment, breathing, developing a strong core, and improving coordination and balance.",
                            Duration = new TimeSpan(0, 1, 30, 0, 0),
                            Name = "Pilates",
                            StartTime = new DateTime(2021, 9, 30, 19, 9, 46, 580, DateTimeKind.Local).AddTicks(5956)
                        },
                        new
                        {
                            Id = 27,
                            Description = "Kickboxing is a group of stand-up combat sports based on kicking and punching, historically developed from karate mixed with boxing. Kickboxing is practiced for self-defence, general fitness, or as a contact sport.",
                            Duration = new TimeSpan(0, 1, 0, 0, 0),
                            Name = "Kickboxing",
                            StartTime = new DateTime(2021, 10, 1, 19, 9, 46, 580, DateTimeKind.Local).AddTicks(5958)
                        },
                        new
                        {
                            Id = 28,
                            Description = "High-intensity interval training (HIIT) is a form of interval training, a cardiovascular exercise strategy alternating short periods of intense anaerobic exercise with less intense recovery periods, until too exhausted to continue. The method is not just restricted to cardio and frequently includes weights for the short periods as well.",
                            Duration = new TimeSpan(0, 0, 30, 0, 0),
                            Name = "HIIT",
                            StartTime = new DateTime(2021, 10, 2, 19, 9, 46, 580, DateTimeKind.Local).AddTicks(5961)
                        },
                        new
                        {
                            Id = 29,
                            Description = "Yoga is a mind-body practice that combines physical poses, controlled breathing, and meditation or relaxation. Yoga may help reduce stress, lower blood pressure and lower your heart rate. And almost anyone can do it.",
                            Duration = new TimeSpan(0, 1, 0, 0, 0),
                            Name = "Yoga",
                            StartTime = new DateTime(2021, 9, 13, 19, 9, 46, 580, DateTimeKind.Local).AddTicks(5963)
                        },
                        new
                        {
                            Id = 30,
                            Description = "Zumba is an interval workout. The classes move between high- and low-intensity dance moves designed to get your heart rate up and boost cardio endurance.",
                            Duration = new TimeSpan(0, 1, 30, 0, 0),
                            Name = "Zumba",
                            StartTime = new DateTime(2021, 9, 7, 19, 9, 46, 580, DateTimeKind.Local).AddTicks(5966)
                        },
                        new
                        {
                            Id = 31,
                            Description = "Boredom and time constraints are frequently cited reasons for giving up on a fitness routine. Sound familiar? Circuit training offers a practical solution for both. It’s a creative and flexible way to keep exercise interesting and saves time while boosting cardiovascular and muscular fitness. ",
                            Duration = new TimeSpan(0, 0, 45, 0, 0),
                            Name = "Circuit",
                            StartTime = new DateTime(2021, 10, 3, 19, 9, 46, 580, DateTimeKind.Local).AddTicks(5968)
                        },
                        new
                        {
                            Id = 32,
                            Description = "Burn up to 1,000 calories while having a blast. Feel that oh-so-rewarding burn in your legs, arms, and core over an hour of fitness disguised as fun. It’s one of the most dynamic, effective, and enjoyable workouts you'll ever have.",
                            Duration = new TimeSpan(0, 0, 45, 0, 0),
                            Name = "Skyrobics",
                            StartTime = new DateTime(2021, 10, 4, 19, 9, 46, 580, DateTimeKind.Local).AddTicks(5970)
                        });
                });

            modelBuilder.Entity("Gymbokning.Models.ViewModels.BookedGymClassViewModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ApplicationUserGymClassIsBooked")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BookedGymClassViewModel");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Gymbokning.Models.ApplicationUserGymClass", b =>
                {
                    b.HasOne("Gymbokning.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("AttendedClasses")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gymbokning.Models.GymClass", "GymClass")
                        .WithMany("AttendingMembers")
                        .HasForeignKey("GymClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("GymClass");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Gymbokning.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Gymbokning.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gymbokning.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Gymbokning.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gymbokning.Models.ApplicationUser", b =>
                {
                    b.Navigation("AttendedClasses");
                });

            modelBuilder.Entity("Gymbokning.Models.GymClass", b =>
                {
                    b.Navigation("AttendingMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
